### PR TITLE
Added Storytel and davidbozjak to interested parties

### PR DESCRIPTION
**Pull request by davidbozjak**

### CODE REVIEW

**Comment by beeme1mr** [comment]
Hi @davidbozjak, thanks for your interest. Could you please update your PR to alphabetically list yourself and StoryTel? Thanks!

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
Requesting changes based on the review feedback from @beeme1mr

**Review by oleg-nenashev — APPROVED** [review]
Fixed ordering

**Comment by oleg-nenashev** [comment]
Welcome aboard @davidbozjak !

**Comment by davidbozjak** [comment]
Thank you and big thank you @oleg-nenashev for fixing the ordering on my behalf. It was a bank holiday weekend in Sweden, I would have gotten to it today otherwise.

**Pull request merged**
