### PR TITLE
Create code of conduct

### PR DESCRIPTION
**Pull request by DavidPHirsch**
Signed-off-by: David Hirsch david.hirsch@dynatrace.com

## This PR

- adding cncf code of conduct

### CODE REVIEW

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
There is already a code of conduct here: https://github.com/open-feature/.github/blob/main/CODE_OF_CONDUCT.md

**Comment by DavidPHirsch** [comment]
yes, but this solution doesn't require any updates to the document as it will link directly to the CNCF code of conduct and will be updated accordingly. If you prefer I can make the change to the .github  as well

**Comment by oleg-nenashev** [comment]
It causes the code of conduct duplication. The CNCF COC and one in OpenFeature use different incompatible versions of the Code of Conduct. So, if you want to adopt the CNCF CoC a wider change is needed

**Comment by DavidPHirsch** [comment]
ok, then I can scrap this PR, but it could still make sense to update the .github coc

**Comment by justinabrahms** [comment]
Closing. I'm supportive of adopting the CNCF one in the .github repo.

**Pull request closed without merging**
