### PR TITLE
add myself to election

### PR DESCRIPTION
**Pull request by konradjniemiec**
## This PR

- adds this new feature

### Related Issues

Fixes #1234523

### CODE REVIEW

**Comment by DavidPHirsch** [comment]
@konradjniemiec you need to sign off on your commit

**Comment by DavidPHirsch** [comment]
the DCO is still failing

**Review by DavidPHirsch — CHANGES_REQUESTED** [review]
PLease fix the DCO

**Comment by beeme1mr** [comment]
I fixed the merge conflict and bypassed DCO since this isn't a code contribution.

**Review by DavidPHirsch — APPROVED** [review]

**Pull request merged**
